FROM harbor.inner.galaxy.ksyun.com/luban/golang:1.21 as builder
ARG COMMIT
ARG VERSION
ARG SERVER_DIR
ARG PKG_NAME="github.com/prometheus"
ARG BRANCH
ARG user
ARG hostname

ENV GOPROXY https://goproxy.cn,direct
WORKDIR /workshop
COPY ./ ./
RUN GoVersion=$(go version) && \
    BuildTime=$(date +"%Y-%m-%d %H:%M:%S") && \
    CGO_ENABLED=0 go build \
    -ldflags "-X 'github.com/prometheus/common/version.Version=${VERSION}' \
    -X '${PKG_NAME}/common/version.Revision=${COMMIT}' \
    -X '${PKG_NAME}/common/version.Branch=${BRANCH}' \
    -X '${PKG_NAME}/common/version.BuildUser=${user}@${hostname}' \
    -X '${PKG_NAME}/common/version.BuildDate=${BuildTime}'" \
    -a -o ./_output/ipmi_exporter ${SERVER_DIR}

FROM alpine:3.18
WORKDIR /app/
COPY --from=builder /workshop/_output/ipmi_exporter ./ipmi_exporter
ENTRYPOINT ["/app/ipmi_exporter"]
