FROM --platform=$BUILDPLATFORM harbor.inner.galaxy.ksyun.com/luban/golang:1.21 as builder
ARG COMMIT
ARG VERSION
ARG SERVER_DIR
ARG PKG_NAME="github.com/prometheus"
ARG BRANCH
ARG user
ARG hostname
ARG TARGETOS
ARG TARGETARCH

ENV GOPROXY https://goproxy.cn,direct
WORKDIR /workshop
COPY ./ ./
RUN GoVersion=$(go version) && \
    BuildTime=$(date +"%Y-%m-%d %H:%M:%S") && \
    CGO_ENABLED=0 GOOS=$TARGETOS GOARCH=$TARGETARCH go build \
    -ldflags "-X 'github.com/prometheus/common/version.Version=${VERSION}' \
    -X '${PKG_NAME}/common/version.Revision=${COMMIT}' \
    -X '${PKG_NAME}/common/version.Branch=${BRANCH}' \
    -X '${PKG_NAME}/common/version.BuildUser=${user}@${hostname}' \
    -X '${PKG_NAME}/common/version.BuildDate=${BuildTime}'" \
    -a -o ./_output/ipmi_exporter ${SERVER_DIR}

FROM --platform=$TARGETPLATFORM harbor.inner.galaxy.ksyun.com/luban/openeuler-minimal:latest
WORKDIR /app/
RUN yum -y install --nodocs --setopt install_weak_deps=0 freeipmi && yum clean all -y
COPY --from=builder /usr/share/zoneinfo/ /usr/share/zoneinfo/
COPY --from=builder /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
COPY --from=builder /workshop/_output/ipmi_exporter ./ipmi_exporter
ENTRYPOINT ["/app/ipmi_exporter"]
